cicd:
  kubectx: # Kubernetes Context name
  dockerhub:
    username: # Dockerhub username
    password: # Dockerhub password token
  github:
    username: # Github username
    password: # Github password or authentication token
alpha:
  kubectx: # Kubernetes Context name
  namespace: default
  rabbit:
    password: # RabbitMQ password
  redis:
    password: # Redis password
  wavefront:
    token: # Wavefront API token
bravo:
  kubectx: # Kubernetes Context name
  namespace: default
  wavefront:
    token: # Wavefront API token
