cicd:
  kubectx: # Kubernetes Context name
alpha:
  kubectx: # Kubernetes Context name
  namespace: default
  rabbit:
    password: # RabbitMQ password
  redis:
    password: # Redis password
  wavefront:
    token: # Wavefront API token
  dockerhub:
    username: # Dockerhub username
    password: # Dockerhub password token
  github:
    username: # Github username
    password: # Github password or authentication token
  spinnaker:
    s3accesskey:
      id: # AWS Access Key ID for accessing the S3 bucket
      secret: # AWS Access Key Secret for accessing the S3 bucket