apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: spring-music
  namespace: kpack
spec:
  tag: fjb4/spring-music
  serviceAccount: kpack-service-account
  successBuildHistoryLimit: 2
  builder:
    name: default-builder
    kind: Builder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/cloudfoundry-samples/spring-music.git
      revision: master
