apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: kubeapps-ENVIRONMENT
spec:
  destination:
    server: 'CLUSTER_URL'
    namespace: kubeapps
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.7.2
    chart: kubeapps
    helm:
      parameters:
      - name: useHelm3
        value: 'true'
      - name: frontend.service.type
        value: 'LoadBalancer'
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
