apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack
secrets:
  - name: dockerhub-creds
  - name: github-creds
---
apiVersion: build.pivotal.io/v1alpha1
kind: Builder
metadata:
  name: default-builder
  namespace: kpack
spec:
  image: gcr.io/paketo-buildpacks/builder:base
  updatePolicy: polling